### PR TITLE
Merge pull request #15 from NicoHaase/symfony5-compatibility

### PR DESCRIPTION
**Pull request by NicoHaase**
This PR makes your package compatible with Symfony 5

### CODE REVIEW

**Comment by rewieer** [comment]
Hey,
thanks for the PR. There's an other one that have been submitted this morning, mind checking it too ?

**Comment by NicoHaase** [comment]
Hehe, haven't seen that when I started working on it ;) My PR fixes the minimal things needed, while also having the Travis tests in mind.

One thing I do not really like about it is the new minimum requirement for PHP. Even if you wanted to release updates in this package, one could not update it on older PHP installations. If there is no good reason for this (besides forcing people to upgrade their installations!), I'd skip this.

If you want me to, I could integrate the return types into my PR, and afterwards you could merge mine. The other idea should contain that the other contributer at least ensures that the Travis testsuite runs without errors

**Comment by rewieer** [comment]
Well I don't like the idea of deprecating this package for Symfony 3 & 4, so I think keeping PHP requirements to 7.1 which seems to be massively adopted looks good to me.
By the way @NicoHaase since you've put some PR from the beginning of this package I would like to give you maintainer's rights if you'd like to keep supporting it without having my validation :)

**Comment by NicoHaase** [comment]
Hi Anthony, thanks for your feedback. I'd be happy to assist in maintaining this package. For the first tiny steps, I've adapted everything from #14, besides dropping support for PHP 7.1

**Comment by rewieer** [comment]
Thanks for accepting ! I've sent you an invitation. When you are ready feel free to merge your PR :)

**Pull request merged**
