### PR TITLE
Added compatibility with symfony 5

### PR DESCRIPTION
**Pull request by jekk0**

### CODE REVIEW

**Comment by rewieer** [comment]
Hey @jekk0, thanks for submitting this PR
I didn't touch to **Symfony** for something like 2 years now so I have no idea where things are. 
Does Symfony requires PHP 7.3 ?

**Comment by jekk0** [comment]
No, it's my mistake. Symfony required php ^7.2.5 according composer file data
https://github.com/symfony/symfony/blob/5.0/composer.json

**Comment by NicoHaase** [comment]
@jekk0 we've just merged a PR that makes this package compatible with Symfony 5. If you want to add anything else, please rebase your PR and tell us what is missing

**Comment by jekk0** [comment]
Thanks, I need compatibility with symfony 5, other changes is not necessary.

**Pull request closed without merging**
